#!/usr/bin/env python

import sys
from misc import *

if len(sys.argv) < 2:
	sys.exit('Need one argument: a .profile filename.')

profile_filename = sys.argv[1]
profile_data_to_svg_file(profile_filename)

