#!/usr/bin/env bash

function do_it_for_sure() {
	for d in $(find -mindepth 1 -maxdepth 1  -type d) ; do 
		if [ "$d" != "./psycopg2" ] ; then
			rm -r "$d"
		fi
	done

	echo local > HOST

	chmod u+x poll_predictions.py
	chmod u+x poll_locations.py
	chmod u+x purgedb.py

	echo 'Write MOFRs?'
	read response
	if [ "$response" == "y" ] ; then
		touch WRITE_MOFRS
	fi


	echo 'Done.'
}

echo 'Are you sure?'
read response
if [ "$response" == "y" ] ; then
	sleep 3
	echo 'Again - are you sure?'
	read response
	if [ "$response" == "y" ] ; then
		do_it_for_sure
	fi
fi

