#!/usr/bin/env bash

if [ "$#" -lt 1 ] ; then
	echo 'Need at least one argument - filename of python script (plus maybe arguments for it).'
	exit 1
fi

python -O -m cProfile -o /tmp/out.profile "$@" && gprof2dot.py -f pstats /tmp/out.profile | dot -Tsvg -o profiler-output.svg && ./add-panzoom-to-svg.py profiler-output.svg



