#!/usr/bin/env bash

if [ "$#" == 1 ] ; then
	file="$1"
	rsync -avz ./"$file" dt@theorem.ca:~/web/ttc-traffic-report/dev2039462378923789/"$file"
elif [ "$#" == 0 ] ; then
	rsync -avz --delete --exclude '.svn' . dt@theorem.ca:~/web/ttc-traffic-report/dev2039462378923789
else
	echo 'Need 0 or 1 arguments.'
fi


