#!/usr/bin/env bash

#if [[ $(pwd) =~ ^/var/www/main.* ]] ; then
#	echo 'Current directory is under /var/www/main.  Cannot continue.'
#	exit 1
#fi
cd /tmp

HOME=~dt

if [ "$#" == "2" ] ; then 
	revision=$1
	branch=$2
	using_cmdline_args=true
elif [ "$#" == "0" ] ; then
	using_cmdline_args=false
else
	echo 'Wrong number of arguments.  Need either a) a revision and a branch, or b) no arguments (will default to head of trunk.)'
	exit 1
fi
export using_cmdline_args
export revision
export branch

function check () {
	if [ "$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

sudo revision=$revision branch=$branch using_cmdline_args=$using_cmdline_args -i -u dt bash << _END_

function check () {
	if [ "\$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

echo 'Synching svn mirror...'
svn_mirror_proj_base_url=\$(~/bin/svn-sync-mirror)
echo '... done.'

if [ "\$using_cmdline_args" != "true" ] ; then
	revision=\$(svn info \$svn_mirror_proj_base_url/trunk | grep '^Revision:' | sed 's/[^01-9]//g')
	branch=trunk
fi

tmpsvndir=\$(mktemp -d --tmpdir=/tmp ttc-main-svn-XXXXXX)

cd ~/svn-mirror-update-main-sandbox
check

if [ "\$using_cmdline_args" != "true" ] ; then
	echo 'Switching to trunk...'
	svn switch "\$svn_mirror_proj_base_url"/trunk
	check
	echo 'Updating to latest revision...'
	svn update
	check
else
	if [ "\$branch" == "trunk" ] ; then
		echo 'Switching to trunk...'
		svn switch "\$svn_mirror_proj_base_url"/trunk
		check
		echo 'Updating to revision' \$revision '...'
		svn update -r \$revision
		check
	else
		echo 'Switching to branch' \$branch '...'
		svn switch "\$svn_mirror_proj_base_url"/branches/\$branch
		check
		echo 'Updating to revision' \$revision '...'
		svn update -r \$revision
		check
	fi
fi
check
echo '... done updating svn sandbox.'
mkdir \$tmpsvndir/main
check
echo 'Copying sandbox content to tmp dir...'
cp -r . \$tmpsvndir/main
check
echo '... done copying.'
cd \$tmpsvndir/main
check
./set-permissions.py 
check
echo 'Mangling...'
./mangle_this_sandbox_make_it_production.py --yes
check
echo '... done mangling.'

echo "\$revision"-"\$branch" > VERSION 

echo 'Priming routeinfos...'
./prime_routeinfos.py
echo '... done.'

echo 'Priming memcache streetlabels...'
./prime_memcache_streetlabels.py
echo '... done.'
_END_

check

apachectl stop
supervisorctl stop ttc-make-reports-main

sudo -i -u dt bash << _END_
tmpsvndir=\$(l -td /tmp/ttc-main-svn-* | head -1)
rm -rf /var/www/main
cd \$tmpsvndir
mv main /var/www
cd /
rm -rf \$tmpsvndir
_END_

apachectl start
supervisorctl start ttc-make-reports-main

echo 'Sleeping for two minutes, to wait for new reports to appear in database...'
sleep 120
echo '... done.'


