#!/usr/bin/env bash

cd /tmp

if [ "$#" == "1" ] ; then 
	revision=$1
elif [ "$#" == "0" ] ; then
	revision=default
else
	echo 'Wrong number of arguments.  Need either a changeset/revision/branch/tag, or no argument.  (Will default to head of default branch.)'
	exit 1
fi

function check () {
	if [ "$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

echo 'Doing pull on mirror...'
cd ~/ttcskycam-bitbucket-mirror
check
hg pull
check
echo '... done.'

echo 'Updating mirror...'
hg up $revision
check
echo '... done.'

VERSION=$(./get-version.py)
check

tmp_sandbox_copy_dir=$(mktemp -d --tmpdir=/tmp ttc-sandbox-copy-for-log-graphs-XXXXXX)

echo 'Copying sandbox content to tmp dir...'
rsync -a --exclude .hg ~/ttcskycam-bitbucket-mirror/ $tmp_sandbox_copy_dir
check
echo '... done copying.'

cd $tmp_sandbox_copy_dir
check
./set-permissions.py 
check
echo 'Mangling...'
./mangle_this_sandbox_make_it_log_graphs.py
check
echo '... done mangling.'

echo $VERSION > VERSION 

for timeframe in month week 3day day ; do 
	./make-log-graph.py $timeframe
	check
done

cd /
rm -rf /var/www/log-graphs
check
mv $tmp_sandbox_copy_dir /var/www/log-graphs
cd /

