#!/usr/bin/env bash

#if [[ $(pwd) =~ ^/var/www/main.* ]] ; then
#	echo 'Current directory is under /var/www/main.  Cannot continue.'
#	exit 1
#fi
cd /tmp

HOME=~dt

if [ "$#" == "1" ] ; then 
	revision=$1
elif [ "$#" == "0" ] ; then
	revision=default
else
	echo 'Wrong number of arguments.  Need either a changeset/revision/branch/tag, or no argument.  (Will default to head of default branch.)'
	exit 1
fi
export revision

function check () {
	if [ "$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

tmpsandboxdir=$(mktemp -d --tmpdir=/tmp ttc-dbman-sandbox-XXXXXX)
chown dt $tmpsandboxdir
chgrp dt $tmpsandboxdir

sudo revision=$revision tmpsandboxdir=$tmpsandboxdir -i -u dt bash << _END_

function check () {
	if [ "\$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

echo 'Doing pull on mirror...'
cd ~/ttcskycam-bitbucket-mirror
check
hg pull
check
echo '... done.'

echo 'Updating mirror...'
hg up \$revision
check
echo '... done.'

VERSION=\$(./get-version.py)

mkdir \$tmpsandboxdir/main
check
echo 'Copying sandbox content to tmp dir...'
rsync -a --exclude .hg ~/ttcskycam-bitbucket-mirror/ \$tmpsandboxdir/main
check
echo '... done copying.'

cd \$tmpsandboxdir/main
check
./set-permissions.py 
check
echo 'Mangling...'
./mangle_this_sandbox_make_it_main.py --yes
check
echo '... done mangling.'

echo \$VERSION > VERSION

echo 'Priming routeinfos...'
./prime_routeinfos.py
check
echo '... done.'

echo 'Priming memcache streetlabels...'
./prime_memcache_streetlabels.py
check
echo '... done.'

echo 'Generating some reports...'
./reports.py --time now
check
echo '... done.'

_END_

check

apachectl stop
supervisorctl stop ttc-make-reports-main

sudo tmpsandboxdir=$tmpsandboxdir -i -u dt bash << _END_

function check () {
	if [ "\$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

cd \$tmpsandboxdir
check
rm -rf /var/www/main
check
mv main /var/www
check
cd /
rm -rf \$tmpsvndir
_END_

apachectl start
supervisorctl start ttc-make-reports-main

