#!/usr/bin/env bash

cd /tmp

if [ "$#" == "2" ] ; then 
	revision=$1
	branch=$2
	using_cmdline_args=true
elif [ "$#" == "0" ] ; then
	using_cmdline_args=false
else
	echo 'Wrong number of arguments.  Need either a) a revision and a branch, or b) no arguments (will default to head of trunk.)'
	exit 1
fi
export using_cmdline_args
export revision
export branch

function check () {
	if [ "$?" != "0" ] ; then echo 'Problem.  Exiting.'; exit 1; fi 
}

echo 'Synching svn mirror...'
svn_mirror_proj_base_url=$(~/bin/svn-sync-mirror)
echo '... done.'

if [ "$using_cmdline_args" != "true" ] ; then
	revision=$(svn info $svn_mirror_proj_base_url/trunk | grep '^Revision:' | sed 's/[^01-9]//g')
	branch=trunk
fi

tmp_sandbox_copy_dir=$(mktemp -d --tmpdir=/tmp ttc-sandbox-copy-for-log-graphs-XXXXXX)

cd ~/svn-mirror-update-prod-log-graphs
check

echo 'Updating sandbox...'
if [ "$branch" == "trunk" ] ; then
	svn switch "$svn_mirror_proj_base_url"/trunk@$revision
	check
else
	svn switch "$svn_mirror_proj_base_url"/branches/$branch@$revision
	check
fi
echo '... done.'

echo 'Copying sandbox content to tmp dir...'
cp -r . $tmp_sandbox_copy_dir
check
echo '... done copying.'

cd $tmp_sandbox_copy_dir
check
./set-permissions.py 
check
echo 'Mangling...'
./mangle_this_sandbox_make_it_production.py --yes
check
echo '... done mangling.'

echo "$revision"-"$branch" > VERSION 

./make-log-graph.py month
check
./make-log-graph.py week
check
./make-log-graph.py 3day
check
./make-log-graph.py day
check

rm -rf /var/www/log-graphs
mv $tmp_sandbox_copy_dir /var/www/log-graphs
cd /
rm -rf $tmp_sandbox_copy_dir
check

